b=[1 -1];
a=[1 0 0.81];
y=[2 2];
xic=filtic(b,a,y);
bx=[0 0.49 0.7];
ax=[1 0 0];
ay=conv(a, ax);
by=conv(b, bx) + conv(xic,ax);
[R p C]=residuez(by,ay);
disp('Residues'), disp(R);
disp('Poles'), disp(p);
disp('Direct Term'), disp(C);
n=0:20;
u1=[n>=-1];
x=((0.7).*n).*u1;
y1=filter(b,a,x);
subplot(2,1,1), plot(n,x), title('x(n)');
subplot(2,1,2), plot(y), title('Response h(n)');
L=30;
[y n] = impz(by,ay,L);
figure;
stem(y), title('Impulse Response, h[n]'); 
grid on;
xlabel('Sample Number'), ylabel('Amplitude');
